apiVersion: v1
kind: Namespace
metadata:
  name: pasteleria-namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pasteleria-serviceaccount
  namespace: pasteleria-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pasteleria-rolebinding
  namespace: pasteleria-namespace
subjects:
- kind: ServiceAccount
  name: pasteleria-serviceaccount
  namespace: pasteleria-namespace
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pasteleriaapi-deployment
  namespace: pasteleria-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pasteleriaapi
  template:
    metadata:
      labels:
        app: pasteleriaapi
    spec:
      nodeSelector:
        role: nodoapp
      containers:
      - name: pasteleriaapi
        image: akscontenedoresdev02.azurecr.io/pasteleriaapi:1.1.0
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080;8081"
---
apiVersion: v1
kind: Service
metadata:
  name: pasteleriaapi-service
  namespace: pasteleria-namespace
spec:
  selector:
    app: pasteleriaapi
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pasteleriportal-deployment
  namespace: pasteleria-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pasteleriportal
  template:
    metadata:
      labels:
        app: pasteleriportal
    spec:
      nodeSelector:
        role: nodoapp
      containers:
      - name: pasteleriportal
        image: akscontenedoresdev02.azurecr.io/pasteleriaportal:1.1.0
        ports:
        - containerPort: 8082
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_HTTP_PORTS
          value: "80;8082"
---
apiVersion: v1
kind: Service
metadata:
  name: pasteleriportal-service
  namespace: pasteleria-namespace
spec:
  selector:
    app: pasteleriportal
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pasteleriaapi-clusterip-service
  namespace: pasteleria-namespace
spec:
  selector:
    app: pasteleriaapi
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
