apiVersion: apps/v1
kind: Deployment
metadata:
  name: pasteleriaapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pasteleriaapi
  template:
    metadata:
      labels:
        app: pasteleriaapi
    spec:
      containers:
      - name: pasteleriaapi
        image: akscontenedoresdev02.azurecr.io/pasteleriaapi:1.0.2
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080;8081"
---
apiVersion: v1
kind: Service
metadata:
  name: pasteleriaapi-service
spec:
  selector:
    app: pasteleriaapi
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pasteleriportal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pasteleriportal
  template:
    metadata:
      labels:
        app: pasteleriportal
    spec:
      containers:
      - name: pasteleriportal
        image: akscontenedoresdev02.azurecr.io/pasteleriaportal:1.0.2
        ports:
        - containerPort: 8082
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_HTTP_PORTS
          value: "80;8082"
---
apiVersion: v1
kind: Service
metadata:
  name: pasteleriportal-service
spec:
  selector:
    app: pasteleriportal
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: LoadBalancer