trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  imageName: 'pasteleriaapi'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'PasteleriaApi/PasteleriaApi.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'PasteleriaApi/PasteleriaApi.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'PasteleriaApi/PasteleriaApi.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'acrtspdev001.azurecr.io/$(imageName)'
    Dockerfile: 'PasteleriaApi/Dockerfile'
    containerRegistry: 'TspAcr'
    tags: |
      $(Build.BuildId)
    buildContext: '$(Build.SourcesDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/publish'
    artifactName: 'drop'