trigger:
- dev

pr:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  imageName: 'pasteleriaapi'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'PasteleriaApi/PasteleriaApi.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'PasteleriaApi/PasteleriaApi.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'Portal/Portal.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Portal/Portal.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'PasteleriaApi/PasteleriaApi.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'pasteleriaapi'
    Dockerfile: 'PasteleriaApi/Dockerfile'
    containerRegistry: 'TspAcr'
    tags: |
      $(Build.BuildId)
      latest
    buildContext: '$(Build.SourcesDirectory)'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'pasteleriportal'
    Dockerfile: 'Portal/Dockerfile'
    containerRegistry: 'TspAcr'
    tags: |
      $(Build.BuildId)
      latest
    buildContext: '$(Build.SourcesDirectory)'

- task: CopyFiles@2
  inputs:
    contents: '**/container-group.yaml'
    targetFolder: '$(Build.ArtifactStagingDirectory)/ContainerInstance'
    flattenFolders: true

- task: CopyFiles@2
  inputs:
    contents: '**/aks-deployment.yaml'
    targetFolder: '$(Build.ArtifactStagingDirectory)/Aks'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'Artefactos'